services:
  - type: web
    name: hyper63-nano
    env: node
    buildCommand: yarn
    startCommand: node index.js
    disk:
      name: hyper63-data
      mountPath: /data
      sizeGB: 10
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: DATA
        value: /data
      - key: SECRET
        generateValue: true
