services:
  - type: web
    name: hyper63-nano
    env: node
    startCommand: node index.js
    disk:
      name: hyper63-data
      mountPath: /data
      sizeGB: 10
    autoDeploy: false
    envVars:
      - key: DATA
        value: /data
